// /lib/mappings.ts

// Mapping pour la catégorie principale du bien
export const propertyCategoryMapping = {
    1: "Vente",
    2: "Location",
    3: "Location saisonnière",
    4: "Programme",
    5: "Viager",
    6: "Enchère",
  };
  
  // Mapping pour la sous-catégorie
  export const propertySubcategoryMapping = {
    1: "Vente à l'unité",
    2: "Vente en bloc",
    21: "Vide",
    22: "Meublée",
    23: "Colocation",
    24: "Étudiant",
    25: "Semi-meublé",
    26: "Co-working",
    31: "Vacances",
    32: "Événementiel",
    41: "Programme neuf",
    51: "Viager libre",
    52: "Viager occupé",
    53: "Nue-propriété",
    54: "Vente à terme",
    55: "Viager semi-occupé",
    56: "Vente à terme libre",
    57: "Vente à terme semi-occupé",
    58: "Vente à terme occupé",
    59: "Viager sans rente",
  };
  
  // Mapping pour le type de bien (général)
  export const propertyTypeMapping = {
    1: "Appartement",
    2: "Maison",
    3: "Terrain",
    4: "Commerce",
    5: "Garage / Parking",
    6: "Immeuble",
    7: "Bureau",
    8: "Bateau",
    9: "Locaux d'activité / Entrepôts",
    10: "Cave / Box",
  };
  
  // Mapping pour le sous-type précis du bien
  export const propertySubtypeMapping = {
    1: "Triplex",
    2: "Terrain constructible",
    3: "Terrain inconstructible",
    4: "Penthouse",
    5: "Appartement",
    6: "Studio",
    7: "Château",
    8: "Commerce",
    9: "Duplex",
    10: "Manoir",
    11: "Ferme",
    12: "Loft",
    13: "Maison de village",
    14: "Villa",
    15: "Appartement villa",
    16: "Grange",
    17: "Ruine",
    18: "Maison",
    19: "Propriété",
    20: "Ensemble immobilier",
    21: "Moulin",
    22: "Garage",
    23: "Fermette",
    24: "Immeuble",
    25: "Maison de ville",
    26: "Mobile home",
    27: "Chaumière",
    28: "Chambre",
    29: "Hangar",
    30: "Mas",
    31: "Local",
    32: "Chalet",
    33: "Local commercial",
    34: "Fonds de commerce",
    35: "Droit au bail",
    36: "Bureau",
    37: "Hôtel particulier",
    38: "Gérance",
    39: "Exploitation agricole",
    40: "Cave",
    41: "Entrepôt",
    42: "Remise",
    43: "Parking",
    44: "Hôtel",
    45: "Haras",
    46: "Terrain",
    47: "Bastide",
    48: "Bastidon",
    49: "Entreprise",
    50: "Propriété viticole",
    51: "Yacht",
    52: "Péniche",
    53: "Voilier",
    54: "Catamaran",
    55: "Domaine équestre",
    56: "Maison d'hôtes",
    57: "Gîte",
    58: "Riad",
    59: "Box",
    60: "Attique",
    61: "Arcade",
    62: "Boutique",
    63: "Atelier",
    64: "Shophouse",
    65: "Borey",
    66: "Condo",
    67: "Usine",
    68: "Appart'hôtel",
    69: "Villa jumelée",
    70: "Maison de plain-pied",
    71: "Maison jumelée",
    72: "Bungalow",
    73: "Maison de plage",
    74: "Place de port",
    75: "Quartier ger",
    76: "Maison d'été",
    77: "Île privée",
    78: "Terrain résidentiel",
    79: "Terrain commercial",
    80: "Lotissement",
    81: "Domaine de chasse",
    82: "Bateau à moteur",
    83: "Pavillon",
    84: "Ranch",
    85: "Lac",
    87: "Atelier artisanal",
    88: "Pavillon",
    89: "Cellier",
    90: "Grenier",
    103: "Terrain agricole",
    104: "Local et fonds de commerce",
    105: "Batiment historique",
  };
  